export const MAIN_COLOR = '#4CAF50'
export const COLOR_BUTTON ='rgb(255,254,202)'
export const COLOR_ITEM_BACKGROUND ='#f5f5f5'
export const COLOR_ITEM_BORDER = '#a9a9a9'
export const COLOR_CANCEL_SOMETHING = 'red'

export const COLOR_ORDER_STATUS_PENDING = '#F39C12' 
export const COLOR_ORDER_STATUS_ACCEPTED = '#18BC9C'
export const COLOR_ORDER_STATUS_CANCELLED = '#E74C3C'
export const COLOR_ORDER_STATUS_COMPLETED = '#3498DB'
export const COLOR_ORDER_STATUS_MISSED = '#323E50'
export const COLOR_ORDER_STATUS_EXPIRED = '#323E50'


